services:
  db:
    image: postgres:16
    container_name: assessment_portal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assessment_portal
    ports:
      - "5432:5432"
    volumes:
      - ap_db:/var/lib/postgresql/data
volumes:
  ap_db:
